%   jeff gray
%   02.28.2016
%   NESC 5330

%   i made this to make plots look awesome! run after plotting.

    %   rip plot data
    varA = findobj(gca, 'Type', 'line');
    varX = get(varA, 'Xdata');
    varY = get(varA, 'Ydata');
    numObj = size(varA, 1);
    
    figure('Units', 'pixels', ...
    'Position', [100 100 500 375]);
    hold on;   

    if (numObj == 1)
        hData(1, 1) = line(varX, varY);
    else
    hData = zeros(numObj, 1);
        for i = 1 : numObj
            hData(i, 1)  = line(varX{i}, varY{i} );
        end
    end

%set(hFit                          , ...
%  'LineWidth'       , 2           );
%set(hE                            , ...
%  'LineWidth'       , 1           , ...
%  'Marker'          , 'o'         , ...
%  'MarkerSize'      , 6           , ...
%  'MarkerEdgeColor' , [.2 .2 .2]  , ...
%  'MarkerFaceColor' , [.7 .7 .7]  );
set(hData(:, 1)                         , ...
  'LineStyle'       , '-'         , ...
  'LineWidth'       , 1.5         , ...
  'Marker'          , 'none'       ); % , ...
%  , 'MarkerSize'      , 5           , ...
%  'MarkerEdgeColor' , 'none'      , ...
%  'MarkerFaceColor' , [.75 .75 1] );


%set(hModel                        , ...
%  'LineWidth'       , 1.5         );
%set(hCI(1)                        , ...
%  'LineWidth'       , 1.5         );
%set(hCI(2)                        , ...
%  'LineWidth'       , 1.5         );

% adjust error bar width
%hE_c                   = ...
%    get(hE     , 'Children'    );
%errorbarXData          = ...
%    get(hE_c(2), 'XData'       );
%errorbarXData(4:9:end) = ...
%    errorbarXData(1:9:end) - 0.2;
%errorbarXData(7:9:end) = ....
%    errorbarXData(1:9:end) - 0.2;
%errorbarXData(5:9:end) = ...
%    errorbarXData(1:9:end) + 0.2;
%errorbarXData(8:9:end) = ...
%    errorbarXData(1:9:end) + 0.2;
%set(hE_c(2), 'XData', errorbarXData);

hTitle  = title ('title');
hXLabel = xlabel('label'                     );
hYLabel = ylabel('label'                      );

%hText   = text(10, 800, ...
%  sprintf('\\it{C = %0.1g \\pm %0.1g (CI)}', ...
%  c, cint(2)-c));

%hLegend = legend( ...
%  [hE, hFit, hData1], ...
%  'Data1 (\mu \pm \sigma)' , ...
%  'Fit of Data1'      , ...
%  'Data2'       , ...               
%  'location', 'NorthWest' );

hLegend = legend( ...
  [hData(:, 1)], ...
  'Data'       , ...               
  'location', 'NorthWest' );

set( gca                       , ...
    'FontName'   , 'Consolas' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Consolas');
set([hLegend, gca]             , ...
    'FontSize'   , 8           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );

%set(gcf, 'PaperPositionMode', 'auto');

    %   hData  = line(xVdata, yVdata )  //   noisy dots
    
    %   hFit = line(xfit  , yfit   )  //  actual data
    %   xdata_m, ydata_m, ydata_s       //   observed data and std error
    %   hE = errorbar(xdata_m, ydata_m, ydata_s) // error bar
    