function [y] = CalcExcitationWithInhibition( weightList, connectionList, inputList, fbWeightList, excitationMatrix, ni, time, K0, Kfb, Kff)

y = sum( weightList .* excitationMatrix(connectionList, time-1)') ...
       / ( sum( weightList .* excitationMatrix(connectionList, time-1)')...
          + K0 + Kfb * round(sum( fbWeightList .* excitationMatrix(1:ni, time-1)')*1000000)/1000000 ... 
          + Kff * sum(inputList) ); %rounding to match NJ
end
